### ISSUE TITLE
Please sort Known packages in `graalpython -m ginstall install --help` output

### ISSUE THREAD

**Issue by paulvi** [oracle/graalpython#230]
`graalpython -m ginstall install --help` currently lists

```
Known packages are pytest, pytest_parallel, py, attrs, pyparsing, packaging, more_itertools, atomicwrites, pluggy, zipp, wcwidth, PyYAML, six, Cython, setuptools, pkgconfig, wheel, protobuf,
Keras_preprocessing, gast, astor, absl_py, mock, Markdown, Werkzeug, h5py, sortedcontainers, hypothesis, setuptools_scm, numpy, dateutil, certifi, idna, chardet, urllib3, requests, lightfm, pytz, pandas, scipy,
cycler, cppy, cassowary, Pillow, matplotlib
```

It is unconvinient to read though this list as it is not sorted.

**Please sort Known packages in `graalpython -m ginstall install --help` output**

---

Can you point to how this list is defnied? And wher eis the logic of `graalpython -m ginstall install --help` ?

**Comment by msimacek** [comment]
Yes, we can sort it. The list is basically hardcoded in the script.
`ginstall` is defined here: https://github.com/oracle/graalpython/blob/master/graalpython/lib-graalpython/modules/ginstall.py

Note if you want to make changes to it, it may be helpful to know a bit of the history explaining why it's doing the things it's doing. Just few months ago, graalpython didn't have any support for SSL/TLS. PyPI package repository only allows HTTPS connections,  it is not possible to download stuff from there without SSL/TLS support. `pip` worked under graalpython, but in order to install anything from PyPI, you had had to setup a local mirror. `ginstall` was mainly created to circumvent the need for a local PyPI mirror. After we've implemented the `ssl` module, we still kept `ginstall` as a convenience script that selects the version of packages that we've tested. But it's not strictly necessary anymore and when we get to the point where we're sufficiently compatible with PyPI packages, we would drop it in favor of using `pip` directly (still far in the future).

**Comment by oroppas** [comment]
My personal experience with `graalpython -m pip install <package>` is overall positive.
For example, we can install `Cython` by simply `graalpython -m pip install Cython`.
`numpy` still cannot be installed by `pip` yet.

**Comment by paulvi** [comment]
@oroppas My personal experience was not so good, as I am just so-so in Python, and diving deeper into packaging and differences between was painful  as learning through failures.

I wonder if someone has system-wide Python 3 installed, with `pip` on path,  
would it be that `pip install Cython` would give other situation  
than `graalpython -m pip install Cython` or `graalpython -m ginstall install Cython` ?

For Cython package status, take a look at #228 Package status summary

**Comment by oroppas** [comment]
The system-wide `pip` from CPython will install the package into its system-wide python installation by default, e.g.
`/usr/lib/python3.9/site-packages/`. `pip` invoked by `graalpython` will install the package into its own directory.
You can change the installation directory by providing options such as `--target <dir>` or `--user` which will install
package under `$HOME/.local`.

So, if your system-wide `pip` installs `Cython` without an option, `graalpython` won't be able to see it.

**Comment by msimacek** [comment]
The recommended way to use graalpython with 3rd party packages is to create a virtualenv.
```graalpython -m venv my-virtualenv```
and activate with:
```source my-virtualenv/bin/activate```
Now when the virtualenv is active, you can run just```pip install whatever``` and it will use graalpython and install into the correct location within the virtalenv.

**Comment by oroppas** [comment]
@msimacek Thank you for complementing comment.

BTW, `graalpython` can install `rich` (https://github.com/willmcgugan/rich) through `pip`.
#204 needs to be addressed for `rich` to be fully functional. Nonetheless, some of the examples
already work

![rich-spinners-example](https://user-images.githubusercontent.com/885380/126411534-634933fa-3acd-4acb-a917-c669d45fdccd.png)

Pretty cool.

**Comment by paulvi** [comment]
Will this go  only to 21.3 ?

**Comment by msimacek** [comment]
Yes. 21.2 has already been released.
